import getopt
import json
import os
import sys

opts, args = getopt.gnu_getopt(sys.argv[1:], 'd:', ['diagnostics-data='])
opt_dict = dict(opts)

diagnostics_file = None

if '--data' in opt_dict:
    diagnostics_file = opt_dict['--data']
elif '-d' in opt_dict:
    diagnostics_file = opt_dict['-d']
else:
    diagnostics_file = os.getenv("XHARNESS_DIAGNOSTICS_PATH")

if not diagnostics_file:
    print("ERROR: Expected path to the diagnostics JSON file generated by XHarness")
    exit(1)

if not os.path.isfile(diagnostics_file):
    print("ERROR: Diagnostics file not found at `{0:s}`".format(diagnostics_file))
    exit(2)

# The JSON should be an array of objects (one per each executed XHarness command)
operations = json.load(open(diagnostics_file))

for op in operations:
    print("{0:s} {1:s} took {2:d}s exited with {3:d}".format(
          op['platform'],
          op['command'],
          # op['target'],
          # op['targetOS'],
          op['duration'],
          op['exitCode']))
