//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SignCheck {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SignCheckResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SignCheckResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.SignCheck.SignCheckResources", typeof(SignCheckResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be null or empty..
        /// </summary>
        internal static string ArgumentNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgumentNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate chain appears valid..
        /// </summary>
        internal static string DetailCertChainValid {
            get {
                return ResourceManager.GetString("DetailCertChainValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to build certificate chain..
        /// </summary>
        internal static string DetailErrorFailedToBuildCertChain {
            get {
                return ResourceManager.GetString("DetailErrorFailedToBuildCertChain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded.
        /// </summary>
        internal static string DetailExcluded {
            get {
                return ResourceManager.GetString("DetailExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File: {0}.
        /// </summary>
        internal static string DetailFile {
            get {
                return ResourceManager.GetString("DetailFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name: {0}.
        /// </summary>
        internal static string DetailFullName {
            get {
                return ResourceManager.GetString("DetailFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hresult={0:x8}.
        /// </summary>
        internal static string DetailHResult {
            get {
                return ResourceManager.GetString("DetailHResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File identified as {0} using file header..
        /// </summary>
        internal static string DetailIdentifyByHeaderAsType {
            get {
                return ResourceManager.GetString("DetailIdentifyByHeaderAsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type: {0} (inferred).
        /// </summary>
        internal static string DetailMiscFileType {
            get {
                return ResourceManager.GetString("DetailMiscFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No StrongName signature (NGEN/CrossGen image)..
        /// </summary>
        internal static string DetailNativeImage {
            get {
                return ResourceManager.GetString("DetailNativeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public key = {0}.
        /// </summary>
        internal static string DetailPublicKeyToken {
            get {
                return ResourceManager.GetString("DetailPublicKeyToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed: {0}.
        /// </summary>
        internal static string DetailSigned {
            get {
                return ResourceManager.GetString("DetailSigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthentiCode signed: {0}.
        /// </summary>
        internal static string DetailSignedAuthentiCode {
            get {
                return ResourceManager.GetString("DetailSignedAuthentiCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StrongName signed: {0}.
        /// </summary>
        internal static string DetailSignedStrongName {
            get {
                return ResourceManager.GetString("DetailSignedStrongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped.
        /// </summary>
        internal static string DetailSkipped {
            get {
                return ResourceManager.GetString("DetailSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped (unsupported file type).
        /// </summary>
        internal static string DetailSkippedUnsupportedFileType {
            get {
                return ResourceManager.GetString("DetailSkippedUnsupportedFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp: {0:MM/dd/yy H:mm:ss} ({1}).
        /// </summary>
        internal static string DetailTimestamp {
            get {
                return ResourceManager.GetString("DetailTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp: Error retrieving timestamp.
        /// </summary>
        internal static string DetailTimestampError {
            get {
                return ResourceManager.GetString("DetailTimestampError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid timestamp.
        /// </summary>
        internal static string DetailTimestampInvalid {
            get {
                return ResourceManager.GetString("DetailTimestampInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp ({0}) outside validity period ({1} to {2})..
        /// </summary>
        internal static string DetailTimestampOutisdeCertValidity {
            get {
                return ResourceManager.GetString("DetailTimestampOutisdeCertValidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp: Skipped.
        /// </summary>
        internal static string DetailTimestampSkipped {
            get {
                return ResourceManager.GetString("DetailTimestampSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple signatures found..
        /// </summary>
        internal static string DetailVsixMultipleSignatures {
            get {
                return ResourceManager.GetString("DetailVsixMultipleSignatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple signatures found ({0}), only the first signature is checked..
        /// </summary>
        internal static string DetailXmlMultipleSignatures {
            get {
                return ResourceManager.GetString("DetailXmlMultipleSignatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Signature element found..
        /// </summary>
        internal static string DetailXmlNoSignature {
            get {
                return ResourceManager.GetString("DetailXmlNoSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking strong name signature..
        /// </summary>
        internal static string DiagCheckingStrongName {
            get {
                return ResourceManager.GetString("DiagCheckingStrongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking timestamp(s)..
        /// </summary>
        internal static string DiagCheckingTimestamps {
            get {
                return ResourceManager.GetString("DiagCheckingTimestamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating folder {0}..
        /// </summary>
        internal static string DiagCreatingFolder {
            get {
                return ResourceManager.GetString("DiagCreatingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting folder {0}..
        /// </summary>
        internal static string DiagDeletingFolder {
            get {
                return ResourceManager.GetString("DiagDeletingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting file contents to {0}.
        /// </summary>
        internal static string DiagExtractingFileContents {
            get {
                return ResourceManager.GetString("DiagExtractingFileContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File will be treated as &apos;{0}&apos;..
        /// </summary>
        internal static string DiagFileHeaderIdentifyExtensionType {
            get {
                return ResourceManager.GetString("DiagFileHeaderIdentifyExtensionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking {0} against the exclusion list..
        /// </summary>
        internal static string DiagFirstExclusion {
            get {
                return ResourceManager.GetString("DiagFirstExclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating exclusion for {0}: {1}.
        /// </summary>
        internal static string DiagGenerateExclusion {
            get {
                return ResourceManager.GetString("DiagGenerateExclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found section header &apos;{0}&apos;..
        /// </summary>
        internal static string DiagSectionHeader {
            get {
                return ResourceManager.GetString("DiagSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping strong name signature check..
        /// </summary>
        internal static string DiagSkippingStrongName {
            get {
                return ResourceManager.GetString("DiagSkippingStrongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examining file header to find applicable verifier..
        /// </summary>
        internal static string DiagVerifyByFileHeader {
            get {
                return ResourceManager.GetString("DiagVerifyByFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HRESULT: {0:x8} ({1}).
        /// </summary>
        internal static string ErrorHResult {
            get {
                return ResourceManager.GetString("ErrorHResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or missing timestamp..
        /// </summary>
        internal static string ErrorInvalidOrMissingTimestamp {
            get {
                return ResourceManager.GetString("ErrorInvalidOrMissingTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add you comment here.
        /// </summary>
        internal static string ExclusionYourComment {
            get {
                return ResourceManager.GetString("ExclusionYourComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file named {0} already exists. The duplicate entry will be ignored..
        /// </summary>
        internal static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was extracted from Binary table..
        /// </summary>
        internal static string FileExtractedFromBinaryTable {
            get {
                return ResourceManager.GetString("FileExtractedFromBinaryTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {0} (parent: {1}).
        /// </summary>
        internal static string ProcessingFile {
            get {
                return ResourceManager.GetString("ProcessingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to build certificate chain..
        /// </summary>
        internal static string VsixChainBuildFailed {
            get {
                return ResourceManager.GetString("VsixChainBuildFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {0} as a WiX bundle..
        /// </summary>
        internal static string WixBundle {
            get {
                return ResourceManager.GetString("WixBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of XML Signature nodes: {0}..
        /// </summary>
        internal static string XmlSignatureNodes {
            get {
                return ResourceManager.GetString("XmlSignatureNodes", resourceCulture);
            }
        }
    }
}
