namespace Microsoft.DotNet.Build.Tasks.Workloads.Tests
{
    // This class is generated by a tool.
    public class ToolsetInfo
    {
        public const string WixExePath = @"{WixExePath}";
        public const string HeatExePath = @"{HeatExePath}";

        public const string DependencyExt = @"{DependencyExt}";
        public const string UIExt = @"{UIExt}";
        public const string UtilExt = @"{UtilExt}";

        public const string SwixTargetsPath = @"{SwixTargetsPath}";
    }
}
