using System;
using System.IO;

namespace Microsoft.DotNet.Build.Tasks.Workloads.Tests
{
    // This class is generated by a tool.
    public class ToolsetInfo
    {
        public static readonly string WixExePath = Path.Combine(AppContext.BaseDirectory, @"testassets\wix\net6.0\any\wix.exe");
        public static readonly string HeatExePath = Path.Combine(AppContext.BaseDirectory, @"testassets\wix\heat\net472\x64\heat.exe");

        public static readonly string DependencyExt = Path.Combine(AppContext.BaseDirectory, @"testassets\wixext\dependency\WixToolset.Dependency.wixext.dll");
        public static readonly string UIExt = Path.Combine(AppContext.BaseDirectory, @"testassets\wixext\ui\WixToolset.UI.wixext.dll");
        public static readonly string UtilExt = Path.Combine(AppContext.BaseDirectory, @"testassets\wixext\util\WixToolset.Util.wixext.dll");

        public const string SwixTargetsPath = @"{SwixTargetsPath}";
    }
}
