phases:
  - template: /eng/build.yml
    parameters:
      name: Windows_NT
      queue:
        name: Hosted VS2017
        parallel: 2
        matrix:
          Build_Debug:
            _BuildConfig: Debug
            _PublishType: none
            _SignType: test
          Build_Release:
            _BuildConfig: Release
            ${{ if in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'PullRequest') }}:
              _PublishType: none
              _SignType: test
            ${{ if notIn(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'PullRequest') }}:
              _PublishType: none
              _SignType: real
  
  - template: /eng/build.yml
    parameters:
      name: Linux
      queue: 
        name: Hosted Linux Preview
        parallel: 2
        matrix:
          Build_Debug:
            _BuildConfig: Debug
            _PublishType: none
            _SignType: test
          Build_Release:
            _BuildConfig: Release
            _PublishType: none
            ${{ if in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'PullRequest') }}:
              _SignType: test
            ${{ if notIn(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'PullRequest') }}:
              _SignType: real
      variables:
        _PREVIEW_VSTS_DOCKER_IMAGE: microsoft/dotnet-buildtools-prereqs:ubuntu-14.04-cross-0cd4667-20170319080304
