phases:
- phase: Windows
  queue:
    name: Hosted VS2017
  steps:
  - script: echo Environment build.reason - %Build_Reason%
  - ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
    - script: echo Template - PullRequest
  - ${{ if eq(variables['Build.Reason'], 'IndividualCI') }}:
    - script: Echo Template - IndividualCI