variables:
  system.debug: true

phases:
- phase: Foo
  queue:
    name: Hosted VS2017
    parallel: 2
    matrix:
      Build_Debug:
        _BuildConfig: Debug
        _TestOnly: True
      Build_Release:
        _BuildConfig: Release
  variables:
    isTest: $(_TestOnly)        
  steps:
  - ${{ if eq(variables['isTest'], 'True') }}:
    - script: echo _TestOnly is true for $(_BuildConfig)
  - ${{ if ne(variables['isTest'], 'True') }}:
    - script: echo _TestOnly is NOT true for $(_BuildConfig), it's %_isTest%
      env:
        _isTest: $(isTest)
  
