variables:
  system.debug: true

phases:
- phase: MyBuild
  queue:
    name: Hosted VS2017
    parallel: 2
    matrix:
      Build_Debug:
        _BuildConfig: Debug
      Build_Release:
        _BuildConfig: Release
  steps:
    - script: echo config - %_BuildConfig%

- phase: MyDependentBuild
  dependsOn: Build_Debug
  steps:
  - script: echo dependent build Debug