phases:
  - template: /eng/build.yml
    parameters:
      name: Windows_NT
      queue:
        # For public or PR jobs, use the hosted pool.  For internal jobs use the internal pool.
        # Will eventually change this to two BYOC pools.
        ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
          name: Hosted VS2017
        ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
          name: dotnet-internal-temp
        parallel: 2
        matrix:
          Build_Debug:
            _BuildConfig: Debug
            _PublishType: none
            _SignType: test
            _DotNetPublishToBlobFeed : false
          Build_Release:
            _BuildConfig: Release
            # PRs or external builds are not signed.
            ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
              _PublishType: none
              _SignType: test
              _DotNetPublishToBlobFeed : false
            ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
              _PublishType: blob
              _SignType: real
              _DotNetPublishToBlobFeed : true

  - template: /eng/build.yml
    parameters:
      name: Linux
      queue:
        # Temporarily, use the linux pool while the hosted preview doesn't have docker support.
        ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
          name: dnceng-linux-external-temp
        ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
          name: dnceng-linux-internal-temp
        demands:
          - agent.os -equals Linux
        parallel: 2
        matrix:
          Build_Debug:
            _BuildConfig: Debug
            _PublishType: none
            _SignType: none
            _DotNetPublishToBlobFeed : false
          Build_Release:
            _BuildConfig: Release
            _PublishType: none
            _SignType: none
            _DotNetPublishToBlobFeed : false
      variables:
        _PREVIEW_VSTS_DOCKER_IMAGE: microsoft/dotnet-buildtools-prereqs:ubuntu-14.04-cross-0cd4667-20170319080304

  - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
    - template: /eng/common/templates/phases/publish-build-assets.yml
      parameters:
        dependsOn:
          - Windows_NT
          - Linux
        queue:
          name: Hosted VS2017
