variables:
  _HelixType: build/product
  ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
    _HelixSource: pr/dotnet/arcade/$(Build.SourceBranch)
  ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
    _TeamName: DotNetCore
    _HelixSource: official/dotnet/arcade/$(Build.SourceBranch)

resources:
  containers:
  - container: LinuxContainer
    image: microsoft/dotnet-buildtools-prereqs:ubuntu-14.04-cross-0cd4667-20170319080304

phases:
  - template: /eng/build.yml
    parameters:
      name: Windows_NT
      queue:
        # For public or PR jobs, use the hosted pool.  For internal jobs use the internal pool.
        # Will eventually change this to two BYOC pools.
        ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
          name: dotnet-external-temp
        ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
          name: dotnet-internal-temp
        parallel: 2
        matrix:
          Build_Debug:
            _BuildConfig: Debug
            _PublishType: none
            _SignType: test
            _DotNetPublishToBlobFeed : false
          Build_Release:
            _BuildConfig: Release
            # PRs or external builds are not signed.
            ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
              _PublishType: none
              _SignType: test
              _DotNetPublishToBlobFeed : false
            ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
              _PublishType: blob
              _SignType: real
              _DotNetPublishToBlobFeed : true

  - template: /eng/build.yml
    parameters:
      name: Linux
      queue:
        container: LinuxContainer
        ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
          name: dnceng-linux-external-temp
        ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
          name: dnceng-linux-internal-temp
        parallel: 2
        matrix:
          Build_Debug:
            _BuildConfig: Debug
            _PublishType: none
            _SignType: none
            _DotNetPublishToBlobFeed : false
          Build_Release:
            _BuildConfig: Release
            _PublishType: none
            _SignType: none
            _DotNetPublishToBlobFeed : false

  - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
    - template: /eng/common/templates/phases/publish-build-assets.yml
      parameters:
        dependsOn:
          - Windows_NT
          - Linux
        queue:
          name: Hosted VS2017
