phases:
  - phase: foo
    steps:
    - script: echo 0
    - template: foo.yml
      parameters:
        steps:
        - template: foo.yml
          parameters:
            steps:
            - script: echo 1
        - script: echo 2
        - template: foo.yml
          parameters:
            steps:
           - script: echo 3
        - script: echo 4
  - script: echo 5