phases:
- phase: First
  queue:
    name: Hosted VS2017
  variables:
    ${{ if eq(variables['System.TeamProject'], 'public') }}:    
      isPublicProject: true
    ${{ if ne(variables['System.TeamProject'], 'public') }}:    
      isPublicProject: false
    ${{ if eq(variables['isPublicProject'], 'true') }}:
      enableTelemetry: false
    ${{ if ne(variables['isPublicProject'], 'true') }}:
      enableTelemetry: true
  steps:
  - script: echo enableTelemetry - %enableTelem%
    env:
      enableTelem: $(enableTelemetry)
