variables:
- name: myName
  value: Chris
phases:
- phase: First
  queue: Hosted VS2017
  steps:
  - script: echo Hello %username%!
    name: greeting
    env:
      username: $(myName)
  

# DotNetCore-Linux pool is not available in dotnet-stage
#- template: /eng/build.yml
#  parameters:
#    agentOs: Linux
#    buildReason: IndividualCI
#    dockerImage: microsoft/dotnet-buildtools-prereqs:ubuntu-14.04-cross-0cd4667-20170319080304
#    queue: 
#      name: DotNetCore-Linux
#      demands:
#        - agent.os -equals Linux
#      parallel: 2
#      matrix:
#        Build_Debug:
#          _BuildConfig: Debug
#          _PublishType: none
#          _SignType: test
#        Build_Release:
#          _BuildConfig: Release
#          _PublishType: none
#          _SignType: test
