trigger: none

schedules:
- cron: 0 12 * * *
  displayName: Daily build
  branches:
    include:
    - main
  always: true

name: $(Date:yyyMMdd)$(Rev:rr)
stages:
  - stage: SynchronizeSecrets
    jobs:
    - job: Synchronize
      displayName: Synchronize secrets
      pool:
        name: NetCore1ESPool-Internal-NoMSI
        demands: ImageOverride -equals 1es-windows-2022

      steps:
      - task: CmdLine@2
        displayName: Run restore.cmd
        inputs:
          script: "restore.cmd"

      - script: $(Build.SourcesDirectory)/.dotnet/dotnet.exe tool restore
        displayName: Restore dotnet tools

      - task: AzureCLI@2
        displayName: Run secret-manager synchronize
        inputs:
          azureSubscription: DotNet Eng Services Secret Manager
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            Get-ChildItem .vault-config/*.yaml |% { dotnet secret-manager synchronize $_}
