trigger: none

schedules:
- cron: 0 12 * * *
  displayName: Daily build
  branches:
    include:
    - main
  always: true

name: $(Date:yyyMMdd)$(Rev:rr)
stages:
  - stage: SynchronizeSecrets
    jobs:
    - job: Synchronize
      displayName: Synchronize secrets
      pool:
        name: NetCore1ESPool-Internal-NoMSI
        demands: ImageOverride -equals 1es-windows-2022

      steps:
      - task: UseDotNet@2
        displayName: Install global.json SDK
        inputs:
          useGlobalJson: false
      
      - task: CmdLine@2
        displayName: Run restore.cmd
        inputs:
          script: 'restore.cmd'

      - task: UseDotNet@2
        displayName: Install .NET 6 runtime
        inputs:
          packageType: runtime
          version: 6.x

      - task: AzureCLI@2
        displayName: Run secret-manager synchronize
        inputs:
          azureSubscription: DotNet Eng Services Secret Manager
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            Get-ChildItem .vault-config/*.yaml |% { dotnet secret-manager synchronize $_}
