<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(NetMinimum)</TargetFramework>
    <PackageType>MSBuildSdk</PackageType>
    <IsPackable>true</IsPackable>
    <IsBuildTaskProject>true</IsBuildTaskProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Tasks.Core" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
  </ItemGroup>


</Project>
