stages:
- stage: validate
  dependsOn: build
  displayName: Validate
  jobs:
  - job:
    displayName: Signing Validation
    pool:
      name: Hosted Windows 2019 with VS2019
    steps:
      - task: DownloadBuildArtifacts@0
        displayName: Download Package Artifacts
        inputs:
          buildType: current
          artifactName: PackageArtifacts

      - task: PowerShell@2
        displayName: Validate
        inputs:
          filePath: eng\common\sdk-task.ps1
          arguments: -task SigningValidation -restore -msbuildEngine dotnet
            /p:PackageBasePath='$(Build.ArtifactStagingDirectory)/PackageArtifacts'
            /p:Configuration=Release
        continueOnError: true
        
  - job:
    displayName: SourceLink Validation
    variables:
      - template: common-variables.yml
    pool:
      name: Hosted Windows 2019 with VS2019
    steps:
      - task: DownloadBuildArtifacts@0
        displayName: Download Blob Artifacts
        inputs:
          buildType: current
          artifactName: BlobArtifacts

      - task: PowerShell@2
        displayName: Validate
        inputs:
          filePath: $(Build.SourcesDirectory)/eng/common/release/sourcelink-validation.ps1
          arguments: -InputPath $(Build.ArtifactStagingDirectory)/BlobArtifacts/ 
            -ExtractPath $(Agent.BuildDirectory)/Extract/ 
            -GHRepoName $(Build.Repository.Name) 
            -GHCommit $(Build.SourceVersion)
            -SourcelinkCliVersion $(SourceLinkCLIVersion)
        continueOnError: true

- template: \eng\common\templates\release\channels\public-dev-release.yml

- template: \eng\common\templates\release\channels\public-validation-release.yml
