jobs:
- job: setupMaestroVars
  displayName: Setup Maestro Vars
  pool:
    name: Hosted Windows 2019 with VS2019
  steps:
    - task: DownloadBuildArtifacts@0
      displayName: Download Release Configs
      inputs:
        buildType: current
        artifactName: ReleaseConfigs

    - task: PowerShell@2
      name: setReleaseVars
      displayName: Set Release Configs Vars
      inputs:
        targetType: inline
        script: |
          . "$(Build.SourcesDirectory)/eng/common/tools.ps1"
             
          $BarId = Get-Content "$(Build.StagingDirectory)/ReleaseConfigs/BARBuildId.txt" 
          Write-Host "##vso[task.setvariable variable=BARBuildId;isoutput=true]$BarId"
           
          $Channels = ""
          Get-Content "$(Build.StagingDirectory)/ReleaseConfigs/Channels.txt" | ForEach-Object { $Channels += "$_ ," }
          Write-Host "##vso[task.setvariable variable=InitialChannels;isoutput=true]$Channels"
