<!-- Licensed to the .NET Foundation under one or more agreements. The .NET Foundation licenses this file to you under the MIT license. -->
<Project>

  <Target Name="SaveTestRunId"
          AfterTargets="CoreTest">
    <ItemGroup>
      <SentJob Update="$(HelixJobId)">
        <TestRunId>$(TestRunId)</TestRunId>
      </SentJob>
    </ItemGroup>
  </Target>

</Project>
