# This file is the main entry point for the Build Promotion build definition.
# These variables should be declared at build queue time:
#
#   - BARBuildId
#   - PromoteToMaestroChannelId
#   - EnableSymbolValidation
#   - EnableSourceLinkValidation
#   - enableNugetValidation
#   - EnableSigningValidation
#   - EnableSDLValidation
#   -   SDLValidationContinueOnError
#   -   SDLValidationCustomParams

trigger: none

variables:
  _DotNetArtifactsCategory: .NETCore

stages:
- template: post-build.yml
  parameters:
    enableSymbolValidation: $(EnableSymbolValidation)
    enableSourceLinkValidation: $(EnableSourceLinkValidation)
    enableNugetValidation: $(EnableNugetValidation)
    enableSigningValidation: $(EnableSigningValidation)
    
    validateDependsOn:
    
    SDLValidationParameters:
      enable: $(EnableSDLValidation)
      continueOnError: $(SDLValidationContinueOnError)
      params: $(SDLValidationCustomParams)
    
    BARBuildId: $(BARBuildId)
    PromoteToMaestroChannelId: $(PromoteToMaestroChannelId)
