# Currently AzDO does not have native support for communicating variables across stages.
# This file implements a workaround to solve that: it reads artifacts containing variable 
# values and then create variables with those values. The job needs to be executed in 
# every stage.
#
# The reason we keep the scripts in this job inlined is to prevent checkout of repositories
# just to download a single file.

jobs:
- job: setupMaestroVars
  displayName: Setup Maestro Vars
  variables:
    - template: common-variables.yml
    - name: BuildId
      value: $[ coalesce(variables.BARBuildId, 0) ]
    - name: PromoteToChannelId
      value: $[ coalesce(variables.PromoteToMaestroChannelId, 0) ]
  pool:
    vmImage: 'windows-2019'
  steps:
    - checkout: none

    - task: DownloadBuildArtifacts@0
      displayName: Download Release Configs
      condition: eq(variables.PromoteToChannelId, 0)
      inputs:
        buildType: current
        artifactName: ReleaseConfigs

    - task: PowerShell@2
      name: setReleaseVars
      displayName: Set Release Configs Vars
      inputs:
        targetType: inline
        script: |
          try {
            if ($Env:PromoteToMaestroChannelId -eq 0) {
              $Content = Get-Content $(Build.StagingDirectory)/ReleaseConfigs/ReleaseConfigs.txt

              $BarId = $Content | Select -Index 0

              $Channels = ""
              $Content | Select -Index 1 | ForEach-Object { $Channels += "$_ ," }
              
              $IsStableBuild = $Content | Select -Index 2

              $AzureDevOpsProject = $Env:System_TeamProject
              $AzureDevOpsBuildDefinitionId = $Env:System_DefinitionId
              $AzureDevOpsBuildId = $Env:Build_BuildId
              $PromoteToMaestroChannelId = 0
            }
            else {
              $buildApiEndpoint = "${Env:MaestroApiEndPoint}/api/builds/${Env:BARBuildId}?api-version=${Env:MaestroApiVersion}"
              $channelApiEndpoint = "${Env:MaestroApiEndPoint}/api/channels/${Env:PromoteToMaestroChannelId}?api-version=${Env:MaestroApiVersion}"

              $apiHeaders = New-Object 'System.Collections.Generic.Dictionary[[String],[String]]'
              $apiHeaders.Add('Accept', 'application/json')
              $apiHeaders.Add('Authorization',"Bearer ${Env:MAESTRO_API_TOKEN}")

              $buildInfo = try { Invoke-WebRequest -Method Get -Uri $buildApiEndpoint -Headers $apiHeaders | ConvertFrom-Json } catch { Write-Host "Error: $_" }

              if (!$buildInfo) {
                Write-Host "Build with BAR ID ${Env:BARBuildId} was not found in BAR!"
                exit 1
              }

              $channelInfo = try { Invoke-WebRequest -Method Get -Uri $channelApiEndpoint -Headers $apiHeaders | ConvertFrom-Json } catch { Write-Host "Error: $_" }

              if (!$channelInfo) {
                Write-Host "Channel with ID ${Env:PromoteToMaestroChannelId} was not found in BAR. Aborting."
                exit 1
              }

              $BarId = $Env:BARBuildId
              $Channels = 'None'

              #TODO: Fix this once this issue is done: https://github.com/dotnet/arcade/issues/3834
              $IsStableBuild = 'False'

              $AzureDevOpsProject = $buildInfo.azureDevOpsProject
              $AzureDevOpsBuildDefinitionId = $buildInfo.azureDevOpsBuildDefinitionId
              $AzureDevOpsBuildId = $buildInfo.azureDevOpsBuildId
              $PromoteToMaestroChannelId = $Env:PromoteToMaestroChannelId
            }

            Write-Host "##vso[task.setvariable variable=BARBuildId;isOutput=true]$BarId"
            Write-Host "##vso[task.setvariable variable=InitialChannels;isOutput=true]$Channels"
            Write-Host "##vso[task.setvariable variable=IsStableBuild;isOutput=true]$IsStableBuild"

            Write-Host "##vso[task.setvariable variable=AzDOProjectName;isOutput=true]$AzureDevOpsProject"
            Write-Host "##vso[task.setvariable variable=AzDOPipelineId;isOutput=true]$AzureDevOpsBuildDefinitionId"
            Write-Host "##vso[task.setvariable variable=AzDOBuildId;isOutput=true]$AzureDevOpsBuildId"
            Write-Host "##vso[task.setvariable variable=PromoteToMaestroChannelId;isOutput=true]$PromoteToMaestroChannelId"
          }
          catch {
            Write-Host $_
            Write-Host $_.Exception
            Write-Host $_.ScriptStackTrace
            exit 1
          }
      env:
        MAESTRO_API_TOKEN: $(MaestroApiAccessToken)
