jobs:
- job: setupMaestroVars
  displayName: Setup Maestro Vars
  variables:
    - name: BuildId
      value: $[ coalesce(variables.BARBuildId, 0) ]
    - name: PromoteToChannelId
      value: $[ coalesce(variables.PromoteToMaestroChannelId, 0) ]
  pool:
    vmImage: 'windows-2019'
  steps:
    - task: DownloadBuildArtifacts@0
      displayName: Download Release Configs
      condition: eq(variables.PromoteToChannelId, 0)
      inputs:
        buildType: current
        artifactName: ReleaseConfigs

    - task: PowerShell@2
      name: setReleaseVars
      displayName: Set Release Configs Vars
      inputs:
        filePath: $(Build.SourcesDirectory)/eng/common/post-build/set-release-configs-vars.ps1
        arguments: -BARBuildId $(BuildId)
          -PromoteToMaestroChannelId $(PromoteToChannelId)
          -MaestroApiAccessToken $(MaestroApiAccessToken)
          -MaestroApiEndPoint $(MaestroApiEndPoint)
          -MaestroApiVersion $(MaestroApiVersion)
