parameters:
- name: oneLocEnabled
  default: false
  type: boolean
- name: microbuildUseESRP
  default: false
  type: boolean

stages:
- stage: build
  displayName: Build
  jobs:
  - ${{ if eq(parameters.oneLocEnabled, true) }}:
    - template: /eng/common/templates-official/job/onelocbuild.yml@self
      parameters:
        MirrorRepo: arcade
        LclSource: lclFilesFromPackage
        LclPackageId: 'LCL-JUNO-PROD-ARCADE'
  - template: /eng/common/templates-official/jobs/jobs.yml@self
    parameters:
      artifacts:
        publish:
          artifacts: true
          logs: true
          manifests: true
      enableMicrobuild: true
      microbuildUseESRP: ${{ parameters.microbuildUseESRP }}
      enableSourceIndex: true
      workspace:
        clean: all
      jobs:
      - job: Windows_NT
        timeoutInMinutes: 90
        strategy:
          matrix:
            Build_Release:
              _BuildConfig: Release
        preSteps:
        - checkout: self
          fetchDepth: 0
          clean: true
        steps:
        - task: NuGetAuthenticate@1
        - script: eng\common\cibuild.cmd
            -configuration $(_BuildConfig)
            -prepareMachine
            $(_InternalBuildArgs)
            /p:Test=false
          displayName: Windows Build / Publish

        - template: /eng/pipelines/templates/steps/recursive-sign.yml@self
          parameters:
            serviceConnectionName: 'DotNetBuildESRP'
            configPath: 'src/Microsoft.DotNet.RecursiveSigning.Cli/signing-config.json'
            inputs: '$(Build.SourcesDirectory)/artifacts/packages/$(_BuildConfig)/**/Microsoft.DotNet.RecursiveSigning.*.nupkg'
            esrpId: '28ec6507-2167-4eaa-a294-34408cf5dd0e'
            esrpClientId: '0ecbcdb7-8451-4cbe-940a-4ed97b08b955'
            esrpTenantId: '975f013f-7f24-47e8-a7d3-abc4752bf346'
            keyVaultName: 'DotNetEngKeyVault'
            certName: 'DotNet-ESRP-AuthSignCert'
            dryRun: false

- stage: ValidateSdk
  displayName: Validate Arcade SDK
  dependsOn: build
  jobs:
  - template: /eng/validate-sdk.yml@self
    parameters:
      microbuildUseESRP: ${{ parameters.microbuildUseESRP }}
      buildArgs: -configuration $(_BuildConfig)
        -prepareMachine
        $(_InternalBuildArgs)
        /p:Test=false

- template: /eng/common/templates-official/post-build/post-build.yml@self
  parameters:
    publishingInfraVersion: 3
    # signing validation will not run, even if the below value is 'true', if the 'PostBuildSign' variable is set to 'true'
    enableSigningValidation: false
    # Sourcelink validation isn't passing for Arcade due to some regressions. This should be
    # enabled back once this issue is resolved: https://github.com/dotnet/arcade/issues/2912
    enableSourceLinkValidation: false
    publishDependsOn:
    - Validate
    - ValidateSdk
