//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SignCheck {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SignCheckResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SignCheckResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.SignCheck.SignCheckResources", typeof(SignCheckResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthentiCode: {0}.
        /// </summary>
        internal static string DetailAuthentiCode {
            get {
                return ResourceManager.GetString("DetailAuthentiCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded: Yes ({0}).
        /// </summary>
        internal static string DetailExcluded {
            get {
                return ResourceManager.GetString("DetailExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File: {0}.
        /// </summary>
        internal static string DetailFile {
            get {
                return ResourceManager.GetString("DetailFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name: {0}.
        /// </summary>
        internal static string DetailFullName {
            get {
                return ResourceManager.GetString("DetailFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A (failed to retrieve).
        /// </summary>
        internal static string DetailNoTimetamp {
            get {
                return ResourceManager.GetString("DetailNoTimetamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed: {0}.
        /// </summary>
        internal static string DetailSigned {
            get {
                return ResourceManager.GetString("DetailSigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped -unsupported.
        /// </summary>
        internal static string DetailSkipped {
            get {
                return ResourceManager.GetString("DetailSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped - unsupported file type.
        /// </summary>
        internal static string DetailSkippedUnsupportedFileType {
            get {
                return ResourceManager.GetString("DetailSkippedUnsupportedFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong Name: {0} ({1}).
        /// </summary>
        internal static string DetailStrongName {
            get {
                return ResourceManager.GetString("DetailStrongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp: {0:MM/dd/yy H:mm:ss} ({1}).
        /// </summary>
        internal static string DetailTimestamp {
            get {
                return ResourceManager.GetString("DetailTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp: skipped.
        /// </summary>
        internal static string DetailTimestampSkipped {
            get {
                return ResourceManager.GetString("DetailTimestampSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking strong name signature..
        /// </summary>
        internal static string DiagCheckingStrongName {
            get {
                return ResourceManager.GetString("DiagCheckingStrongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking timestamp(s)..
        /// </summary>
        internal static string DiagCheckingTimestamps {
            get {
                return ResourceManager.GetString("DiagCheckingTimestamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating folder {0}..
        /// </summary>
        internal static string DiagCreatingFolder {
            get {
                return ResourceManager.GetString("DiagCreatingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting folder {0}..
        /// </summary>
        internal static string DiagDeletingFolder {
            get {
                return ResourceManager.GetString("DiagDeletingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting file contents to {0}.
        /// </summary>
        internal static string DiagExtractingFileContents {
            get {
                return ResourceManager.GetString("DiagExtractingFileContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found section header &apos;{0}&apos;..
        /// </summary>
        internal static string DiagSectionHeader {
            get {
                return ResourceManager.GetString("DiagSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping strong name signature check..
        /// </summary>
        internal static string DiagSkippingStrongName {
            get {
                return ResourceManager.GetString("DiagSkippingStrongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add you comment here.
        /// </summary>
        internal static string ExclusionYourComment {
            get {
                return ResourceManager.GetString("ExclusionYourComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {0} (parent: {1}).
        /// </summary>
        internal static string ProcessingFile {
            get {
                return ResourceManager.GetString("ProcessingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {0} as a WiX bundle..
        /// </summary>
        internal static string WixBundle {
            get {
                return ResourceManager.GetString("WixBundle", resourceCulture);
            }
        }
    }
}
