parameters:
  # Optional: Clean sources before building
  clean: true

  # Optional: Git fetch depth
  fetchDepth: ''

  # Optional: name of the phase (not specifying phase name may cause name collisions)
  name: ''

  # Required: A defined YAML queue
  queue: {}

  # Required: build steps
  steps: []

  # Optional: variables
  variables: {}

  ## Telemetry variables

  # Optional: enable sending telemetry
  #           if enabled, these "variables" must be specified in the variables object
  #             _HelixBuildConfig - differentiate between Debug, Release, other
  #             _HelixSource - Example: build/product
  #             _HelixType - Example: official/dotnet/arcade/$(Build.SourceBranch)
  enableTelemetry: false

  # Build.Reason for anonymous builds - https://docs.microsoft.com/en-us/vsts/pipelines/build/variables?view=vsts#build-variables
  publicBuildReasons: IndividualCI,BatchedCI,PullRequest

phases:
- phase: ${{ parameters.name }}

  queue: ${{ parameters.queue }}

  ${{ if ne(parameters.variables, '') }}:
    variables: ${{ parameters.variables }}

  steps:
  - checkout: self
    clean: ${{ parameters.clean }}
    ${{ if ne(parameters.fetchDepth, '') }}:
      fetchDepth: ${{ parameters.fetchDepth }}

  - ${{ if eq(parameters.enableTelemetry, 'true') }}:
    # Remove this condition once telemetry can be sent from public CI
    - ${{ if not(contains(parameters.publicBuildReasons, variables['Build.Reason'] )) }}:
      - template: /eng/common/templates/steps/telemetry-start.yml
        parameters:
          buildConfig: ${{ parameters.variables._HelixBuildConfig }}
          helixSource: ${{ parameters.variables._HelixSource }}
          helixType: ${{ parameters.variables._HelixType }}

  # Run provided build steps
  - ${{ parameters.steps }}

  - ${{ if eq(parameters.enableTelemetry, 'true') }}:
    # Remove this condition once telemetry can be sent from public CI
    - ${{ if not(contains(parameters.publicBuildReasons, variables['Build.Reason'] )) }}:
      - template: /eng/common/templates/steps/telemetry-end.yml
        parameters:
          helixSource: ${{ parameters.variables._HelixSource }}
          helixType: ${{ parameters.variables._HelixType }}