storageLocation:
  type: azure-key-vault
  parameters:
    subscription: a4fc5514-21a9-4296-bfaf-5c7ee7fa35d1
    name: dnceng-pipeline-secrets

secrets:
  #DotNet-DotNetCli-Storage
  dotnetcli-storage-key:
    type: text
    parameters:
      description: set to never expire

  dotnetclichecksums-storage-key:
    type: text
    parameters:
      description: set to never expire

  #DotNet-MSRC-Storage
  dotnetbuilddropsmsrc-access-key:
    type: text
    parameters:
      description: set to never expire

  dotnetclichecksumsmsrc-storage-key:
    type: text
    parameters:
      description: set to never expire

  dotnetclimsrc-access-key:
    type: text
    parameters:
      description: set to never expire

  dotnetclimsrc-private-feed-url:
    type: text
    parameters:
      description: set to never expire

  dotnetclimsrc-connection-string:
    type: azure-storage-connection-string
    parameters:
      storageKeySecret: dotnetclimsrc-access-key
      subscription: #TO-DO
      account: dotnetclimsrc

  dotnetclimsrc-read-sas-token:
    type: azure-storage-container-sas-token
    parameters:
      connectionString: dotnetclimsrc-connection-string
      permissions: rl
      container: #TO-DO

  dotnetclimsrc-read-sas-token-base64:
    type: base64-encoder
    parameters:
      secret: dotnetclimsrc-read-sas-token

  dotnetfeedmsrc-private-feed-url:
    type: text
    parameters:
      description: set to never expire

  dotnetfeedmsrc-storage-access-key-1:
    type: text
    parameters:
      description: set to never expire

  dotnetfeedmsrc-connection-string:
    type: azure-storage-connection-string
    parameters:
      storageKeySecret: dotnetfeedmsrc-storage-access-key-1
      subscription: a4fc5514-21a9-4296-bfaf-5c7ee7fa35d1
      account: dotnetfeedmsrc

  dotnetfeedmsrc-read-sas-token:
    type: azure-storage-container-sas-token
    parameters:
      connectionString: dotnetfeedmsrc-connection-string
      permissions: r
      container: #TO-DO

  dotnetfeedmsrc-read-sas-token-base64:
    type: base64-encoder
    parameters:
      secret: dotnetfeedmsrc-read-sas-token