storageLocation:
  type: azure-key-vault
  parameters:
    subscription: a4fc5514-21a9-4296-bfaf-5c7ee7fa35d1
    name: dnceng-pipeline-secrets

references:
  engKeyVault:
    type: azure-key-vault
    parameters:
      subscription: a4fc5514-21a9-4296-bfaf-5c7ee7fa35d1
      name: EngKeyVault

secrets:
  BotAccount-dotnet-maestro-bot-no-scopes-PAT:
    type: github-access-token
    parameters:
      gitHubBotAccountSecret:
        location: engKeyVault
        name: BotAccount-dotnet-maestro-bot
      gitHubBotAccountName: dotnet-maestro-bot
  
  # public_repo scopes (classic token)
  # Used in dotnet-comment-bot-service-connection in dnceng-public
  BotAccount-dotnet-comment-bot-public-PAT:
    type: github-access-token
    parameters:
      gitHubBotAccountSecret:
        location: engKeyVault
        name: BotAccount-dotnet-comment-bot
      gitHubBotAccountName: dotnet-comment-bot

  #DotNet-DotNetCli-Storage
  dotnetcli-storage-key:
    type: text
    parameters:
      description: set to never expire

  dotnetclichecksums-storage-key:
    type: text
    parameters:
      description: set to never expire

  #DotNet-MSRC-Storage
  dotnetbuilddropsmsrc-access-key:
    type: text
    parameters:
      description: set to never expire

  dotnetclichecksumsmsrc-storage-key:
    type: text
    parameters:
      description: set to never expire
      
  dotnetclichecksumsmsrc-connection-string:
    type: azure-storage-connection-string
    parameters:
      storageKeySecret: dotnetclichecksumsmsrc-storage-key
      account: dotnetclichecksumsmsrc
      
  dotnetclichecksumsmsrc-dotnet-container-uri:
    type: azure-storage-container-sas-uri
    parameters:
      connectionString: dotnetclichecksumsmsrc-connection-string
      permissions: rlwc
      container: dotnet

  dotnetclichecksumsmsrc-dotnet-container-uri-base64:
    type: base64-encoder
    parameters:
      secret: dotnetclichecksumsmsrc-dotnet-container-uri

  dotnetclimsrc-access-key:
    type: text
    parameters:
      description: set to never expire

  dotnetclimsrc-connection-string:
    type: azure-storage-connection-string
    parameters:
      storageKeySecret: dotnetclimsrc-access-key
      account: dotnetclimsrc

  dotnetclimsrc-read-uri-token:
    type: azure-storage-container-sas-token
    parameters:
      connectionString: dotnetclimsrc-connection-string
      permissions: rl
      container: dotnet

  dotnetclimsrc-read-sas-token-base64:
    type: base64-encoder
    parameters:
      secret: dotnetclimsrc-read-sas-token
      
  dotnetclimsrc-read-sas-token:
    type: azure-storage-container-sas-token
    parameters:
      connectionString: dotnetclimsrc-connection-string
      permissions: rl
      container: dotnet

  dotnetclimsrc-read-sas-token-base64:
    type: base64-encoder
    parameters:
      secret: dotnetclimsrc-read-sas-token
      
  dotnetclimsrc-dotnet-container-uri:
    type: azure-storage-container-sas-uri
    parameters:
      connectionString: dotnetclimsrc-connection-string
      permissions: rlwc
      container: dotnet

  dotnetclimsrc-dotnet-container-uri-base64:
    type: base64-encoder
    parameters:
      secret: dotnetclimsrc-dotnet-container-uri

  dotnetfeedmsrc-storage-access-key-1:
    type: text
    parameters:
      description: set to never expire

  dotnetfeedmsrc-connection-string:
    type: azure-storage-connection-string
    parameters:
      storageKeySecret: dotnetfeedmsrc-storage-access-key-1
      account: dotnetfeedmsrc

  dotnetfeedmsrc-read-sas-token:
    type: azure-storage-container-sas-token
    parameters:
      connectionString: dotnetfeedmsrc-connection-string
      permissions: r
      container: $root

  dotnetfeedmsrc-read-sas-token-base64:
    type: base64-encoder
    parameters:
      secret: dotnetfeedmsrc-read-sas-token

  # Service Principal used by the Guardian APIScan build task
  apiscan-service-principal:
    type: ad-application
