storageLocation:
  type: azure-key-vault
  parameters:
    subscription: a4fc5514-21a9-4296-bfaf-5c7ee7fa35d1
    name: EngKeyVault

references:
  helixkv:
    type: azure-key-vault
    parameters:
      subscription: a4fc5514-21a9-4296-bfaf-5c7ee7fa35d1
      name: helixkv

secrets:
  BotAccount-dotnet-maestro-bot:
    type: github-account
    parameters:
      Name: dotnet-maestro-bot

  BotAccount-dotnet-bot:
    type: github-account
    parameters:
      Name: dotnet-bot

  #Publish-Build-Assets
  BotAccount-dotnet-maestro-bot-PAT:
    type: github-access-token
    parameters:
      gitHubBotAccountSecret: BotAccount-dotnet-maestro-bot
      gitHubBotAccountName: dotnet-maestro-bot

  BotAccount-dotnet-bot-repo-PAT:
    type: github-access-token
    parameters:
      gitHubBotAccountSecret: BotAccount-dotnet-bot
      gitHubBotAccountName: dotnet-bot

  dn-bot-dnceng-build-rw-code-rw:
    type: azure-devops-access-token
    parameters:
      domainAccountName: dn-bot
      domainAccountSecret:
          location: helixkv
          name: dn-bot-account-redmond
      name: dn-bot-dnceng-build
      organizations: dnceng
      scopes: build_execute code_write

  akams-client-id:
    type: text
    parameters:
      description: Client id for akams app

  dn-bot-dotnet-build-rw-code-rw:
    type: azure-devops-access-token
    parameters:
      domainAccountName: dn-bot
      domainAccountSecret:
          location: helixkv
          name: dn-bot-account-redmond
      name: dn-bot-dotnet-build
      organizations: dnceng
      scopes: build_execute code_write 

  dn-bot-all-orgs-build-rw-code-rw:
    type: azure-devops-access-token
    parameters:
      domainAccountName: dn-bot
      domainAccountSecret:
          location: helixkv
          name: dn-bot-account-redmond
      name: dn-bot-all-orgs-build
      organizations: dnceng devdiv microsoft dotnet-security-partners
      scopes: build_execute code_write

  #DotNet-AllOrgs-Darc-Pats
  dn-bot-devdiv-dnceng-rw-code-pat:
    type: azure-devops-access-token
    parameters:
      domainAccountName: dn-bot
      domainAccountSecret:
          location: helixkv
          name: dn-bot-account-redmond
      name: dn-bot-devdiv-dnceng
      organizations: dnceng devdiv
      scopes: code_write

  #AzureDevOps-Artifact-Feeds-Pats
  dn-bot-dnceng-artifact-feeds-rw:
    type: azure-devops-access-token
    parameters:
      domainAccountName: dn-bot
      domainAccountSecret:
          location: helixkv
          name: dn-bot-account-redmond
      name: dn-bot-dnceng-artifact-feeds
      organizations: dnceng
      scopes: packaging_write

  dn-bot-dnceng-universal-packages-rw:
    type: azure-devops-access-token
    parameters:
      domainAccountName: dn-bot
      domainAccountSecret:
          location: helixkv
          name: dn-bot-account-redmond
      name: dn-bot-dnceng-universal-packages
      organizations: dnceng
      scopes: packaging_write

  dn-bot-all-orgs-artifact-feeds-rw:
    type: azure-devops-access-token
    parameters:
      domainAccountName: dn-bot
      domainAccountSecret:
          location: helixkv
          name: dn-bot-account-redmond
      name: dn-bot-all-orgs-artifact-feeds
      organizations: dnceng devdiv microsoft dotnet-security-partners
      scopes: packaging_write
  
  dn-bot-devdiv-drop-rw-code-rw:
    type: azure-devops-access-token
    parameters:
      domainAccountName: dn-bot
      domainAccountSecret:
          location: helixkv
          name: dn-bot-account-redmond
      name: dn-bot-devdiv-drop-rw-code-rw
      organizations: devdiv
      scopes: code_write drop_write

  dn-bot-devdiv-drop-r-code-r:
    type: azure-devops-access-token
    parameters:
      domainAccountName: dn-bot
      domainAccountSecret:
          location: helixkv
          name: dn-bot-account-redmond
      name: dn-bot-devdiv-drop-r-code-r
      organizations: devdiv
      scopes: code drop

  #DotNet-Symbol-Server-Pats
  microsoft-symbol-server-pat:
    type: azure-devops-access-token
    parameters:
      domainAccountName: dn-bot
      domainAccountSecret:
          location: helixkv
          name: dn-bot-account-redmond
      name: microsoft-symbol-server-pat
      organizations: microsoftpublicsymbols
      scopes: symbols_write  

  symweb-symbol-server-pat:
    type: azure-devops-access-token
    parameters:
      domainAccountName: dn-bot
      domainAccountSecret:
          location: helixkv
          name: dn-bot-account-redmond
      name: dn-symweb-symbol-server-pat
      organizations: microsoft
      scopes: symbols_write

  dnceng-symbol-server-pat:
    type: azure-devops-access-token
    parameters:
      domainAccountName: dn-bot
      domainAccountSecret:
          location: helixkv
          name: dn-bot-account-redmond
      name: dn-bot-dnceng-symbol-server-pat
      organizations: dnceng
      scopes: symbols_manage

  #OneLocBuildVariables
  dn-bot-ceapex-package-r:
    type: azure-devops-access-token
    parameters:
      domainAccountName: dn-bot
      domainAccountSecret:
          location: helixkv
          name: dn-bot-account-redmond
      name: dn-bot-ceapex-package-r
      organizations: ceapex
      scopes: packaging

  # Token used for installing the Guardian CLI from the securitytools AzDO org
  # The PAT is in the Guardian service connections in dnceng and devdiv:
  # https://devdiv.visualstudio.com/DevDiv/_settings/adminservices?resourceId=e002c3af-b8a4-4ebe-816b-d4908648a66a
  # https://dev.azure.com/dnceng/internal/_settings/adminservices?resourceId=d2604fd5-04f1-4957-afe3-3d3ea81a665b
  dn-bot-securitytools-packaging-r:
    type: azure-devops-access-token
    parameters:
      domainAccountName: dn-bot
      domainAccountSecret:
          location: helixkv
          name: dn-bot-account-redmond
      name: dn-bot-securitytools-packaging-r
      organizations: securitytools
      scopes: packaging
