storageLocation:
  type: azure-key-vault
  parameters:
    subscription: a4fc5514-21a9-4296-bfaf-5c7ee7fa35d1
    name: dnceng-pipeline-secrets


secrets:
  #DotNet-DotNetCli-Storage
  dotnetcli-storage-key:
    type: text
    parameters:
      description: set to never expire

  dotnetclichecksums-storage-key:
    type: text
    parameters:
      description: set to never expire


  #DotNet-MSRC-Storage
  dotnetbuilddropsmsrc-access-key:
    type: text
    parameters:
      description: set to never expire

  dotnetclichecksumsmsrc-storage-key:
    type: text
    parameters:
      description: set to never expire

  dotnetclimsrc-access-key:
    type: text
    parameters:
      description: set to never expire

  dotnetclimsrc-private-feed-url:
    type: text
    parameters:
      description: set to never expire

  dotnetclimsrc-read-sas-token:
    type: text
    parameters:
      description: set to never expire

  dotnetclimsrc-read-sas-token-base64:
    type: text
    parameters:
      description: set to never expire

  dotnetfeedmsrc-private-feed-url:
    type: text
    parameters:
      description: set to never expire

  dotnetfeedmsrc-read-sas-token-base64:
    type: text
    parameters:
      description: set to never expire

  dotnetfeedmsrc-storage-access-key-1:
    type: text
    parameters:
      description: set to never expire





