storageLocation:
  type: azure-key-vault
  parameters:
    subscription: a4fc5514-21a9-4296-bfaf-5c7ee7fa35d1
    name: dnceng-pipeline-secrets

references:
  engKeyVault:
    type: azure-key-vault
    parameters:
      subscription: a4fc5514-21a9-4296-bfaf-5c7ee7fa35d1
      name: EngKeyVault

secrets:
  BotAccount-dotnet-maestro-bot-no-scopes-PAT:
    type: github-access-token
    parameters:
      gitHubBotAccountSecret:
        location: engKeyVault
        name: BotAccount-dotnet-maestro-bot
      gitHubBotAccountName: dotnet-maestro-bot
  
  # public_repo scopes (classic token)
  # Used in dotnet-comment-bot-service-connection in dnceng-public
  BotAccount-dotnet-comment-bot-public-PAT:
    type: github-access-token
    parameters:
      gitHubBotAccountSecret:
        location: engKeyVault
        name: BotAccount-dotnet-comment-bot
      gitHubBotAccountName: dotnet-comment-bot

  #DotNet-DotNetCli-Storage
  dotnetcli-storage-key:
    type: text
    parameters:
      description: set to never expire

  dotnetclichecksums-storage-key:
    type: text
    parameters:
      description: set to never expire

  # Service Principal used by the Guardian APIScan build task
  apiscan-service-principal:
    type: ad-application
