jobs:
- job:
  displayName: Post-build Checks
  dependsOn: setupMaestroVars
  variables:
    - name: TargetChannels
      value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.TargetChannels'] ]
  pool:
    vmImage: 'windows-2019'
  steps:
    - task: PowerShell@2
      displayName: Maestro Channels Consistency
      inputs:
        targetType: inline
        script: |
          try {
            $ErrorActionPreference = 'Stop'
            Set-StrictMode -Version 2.0

            # `tools.ps1` requires $ci to be $true
            $ci = $true
            . ${Env:BUILD_SOURCESDIRECTORY}\eng\common\tools.ps1

            if ($Env:TargetChannels -eq "") {
              Write-PipelineTaskError -Type 'warning' -Message "This build won't publish assets as it's not configured to any Maestro channel. If that wasn't intended use Darc to configure a default channel using add-default-channel for this branch or to promote it to a channel using add-build-to-channel. See https://github.com/dotnet/arcade/blob/master/Documentation/Darc.md#assigning-an-individual-build-to-a-channel for more info."
              ExitWithExitCode 0
            }
          } 
          catch {
            Write-Host $_
            Write-PipelineTelemetryError -Category 'CheckChannelConsistency' -Message "There was an error while trying to check consistency of Maestro default channels for the build and post-build YAML configuration."
            ExitWithExitCode 1
          }
