# This is a workflow file that will be used to merge branches in the repository.
# Permissions required: 
#   Contents
#     write
#   Pull requests 
#     write
# More information on permissions: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
# 
# Event data: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_call received is equal to the caller event data. 
# In order to understand which version of script needs to be used parameter script version introduced, which should be equal to the ref of referenced workflow file.
# More information on the script_version:
#   https://github.com/orgs/community/discussions/18601
#   https://github.com/orgs/community/discussions/63863

on:
  workflow_call:
    inputs:      
      base_branch:
        type: string
        description: The branch to merge changes into
        required: true
      allowAutomatedCommits:
        type: boolean
        description: To allow the commits made by the dotnet-maestro[bot]. Applied only when all changes in current branch made by bot. Default is false.
        required: false
        default: false
      quietComments:
        type: boolean
        required: false
        description: Do not tag authors of the original PRs and do produce comments when existing PR is updated. Reduces GitHub notifications noise on the new (automated) PR
        default: true
      script_version:
        type: string
        required: false
        description: Optional parameter which allows the target repository to use different branch of this shared workflow.
        default: 'main'

jobs:
  run-merge:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout caller repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: repository
          fetch-depth: 0
      - name: Checkout arcade repository
        uses: actions/checkout@v4
        with:
          repository: dotnet/arcade
          path: arcade-repository 
          ref: ${{ inputs.script_version }}
          sparse-checkout: |
            .github

      - name: Switch parameters setting
        id: switch-parameters
        run: | 
          $mergeSwitchArguments = ""

          if ('${{ inputs.allowAutomatedCommits }}' -eq 'true') {
            $mergeSwitchArguments = "-AllowAutomatedCommits"
          }else{
            Write-Host "AllowAutomatedCommits is set to False"
          }

          if ('${{ inputs.quietComments }}' -eq 'true') {
            $mergeSwitchArguments = $mergeSwitchArguments + " -QuietComments"
          }else{
            Write-Host "QuietComments is set to False"
          }

          "mergeSwitchArguments=$mergeSwitchArguments" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Fetch repository name
        id: fetch-repo-name
        run: |
          $repoName = "${{ github.repository }}"
          $repoNameWithoutOwner = $repoName.Substring("${{ github.repository_owner }}".Length + 1)
          "repository_name=$repoNameWithoutOwner" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      
      - run: ${{ github.workspace }}\arcade-repository\.github\workflows\scripts\inter-branch-merge.ps1 -RepoName ${{ steps.fetch-repo-name.outputs.repository_name }} -RepoOwner ${{ github.repository_owner }} -HeadBranch $env:GITHUB_REF_NAME -BaseBranch ${{ inputs.base_branch }} ${{ steps.switch-parameters.outputs.mergeSwitchArguments }}
        name: Merge branches
        working-directory: ${{ github.workspace }}/repository
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}