WScript.Echo("Hello");

// SIG // Begin signature block
// SIG // MIIFmQYJKoZIhvcNAQcCoIIFijCCBYYCAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // 4AHLnnu2clp45zTHEm9yCWt+E3gZbUsSWuTj6lYSq5Kg
// SIG // ggMUMIIDEDCCAfigAwIBAgIQTVOqMXY0qrxCMCMgYHdU
// SIG // YTANBgkqhkiG9w0BAQsFADAgMR4wHAYDVQQDDBVBcmNh
// SIG // ZGUgU2lnbkNoZWNrIFRlc3QwHhcNMjYwODIwMTY1MjI4
// SIG // WhcNMjcwODIwMTcxMjI4WjAgMR4wHAYDVQQDDBVBcmNh
// SIG // ZGUgU2lnbkNoZWNrIFRlc3QwggEiMA0GCSqGSIb3DQEB
// SIG // AQUAA4IBDwAwggEKAoIBAQDOFK5I7cH7cMvVQQ2s6ZED
// SIG // 1hj4lSMS0FebIztG/4SZYtDU7TJ9Rz2F+VcN+vCTkOlu
// SIG // 6NztmSJror6KBH3Q8TeG9acWcOITWWiVFBHtTOSSPSkv
// SIG // qMZ4RlTRSjqUbQSOb12dmj9Qm5/LDqjudsIAMWUwj/k6
// SIG // oSUUJ/a3gn88oh4Q3D1U1Q972HNyEreNHTWqLeQOYIKX
// SIG // mUd57whMQkoeFYX3LT9zJGIYbI6RHDmkywBQlQwAEmmb
// SIG // KRi8X2fZ+PL1WK7Nu+gd3oimtDPzELyf9VqGmNayKGWf
// SIG // zZbu/O63k/Dod/wFqTpdl2e8HMLFMUcm5QjM27uPep7x
// SIG // cXEACq/7E1gRAgMBAAGjRjBEMA4GA1UdDwEB/wQEAwIH
// SIG // gDATBgNVHSUEDDAKBggrBgEFBQcDAzAdBgNVHQ4EFgQU
// SIG // cXbEzPngK27h87otkIZ0rf5qmJMwDQYJKoZIhvcNAQEL
// SIG // BQADggEBAIkgrC73snAu0COUsmNrE/yQkx+h+h5//TIE
// SIG // AzdRo4zwB8kVD2Xh6tIjiKqTHi5vSTHN6iBDjxeWRrw8
// SIG // ijWlqOkH/ed+XwBqCOCY6JQh1N2KjJfPagDFhQqFdmAg
// SIG // +loJGvx+ckdvh+ej83zsmfyCkfKPVfjUEyETa1dK4LZo
// SIG // 69iz+piRkYPmENM842tBAZqgY2tuqkVHIWIr7+K9fw9j
// SIG // pgxQmrR2QJrwdBWNvgAISMPZzZ+MVR8W3QzZhu+sYHsc
// SIG // amdM+lh6uTsG7VhA5XHbR7gbSC3MAXOawXtZbJWKDrQg
// SIG // S/ctGaMPVN2d1xXZA8C16qloYRnOAak79TfUGcvu92Mx
// SIG // ggHdMIIB2QIBATA0MCAxHjAcBgNVBAMMFUFyY2FkZSBT
// SIG // aWduQ2hlY2sgVGVzdAIQTVOqMXY0qrxCMCMgYHdUYTAN
// SIG // BglghkgBZQMEAgEFAKB8MBAGCisGAQQBgjcCAQwxAjAA
// SIG // MBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisG
// SIG // AQQBgjcCAQsxDjAMBgorBgEEAYI3AgEVMC8GCSqGSIb3
// SIG // DQEJBDEiBCCpLzRxSVbZsN45PM/66sSuw0SoO172uYkH
// SIG // 2b12nBEovjANBgkqhkiG9w0BAQEFAASCAQAcnSB3fUV0
// SIG // 5ug19X46nplElF3BKH+M3q1OkSZ3HLxF1g13OOUyM/SM
// SIG // Jk2P4XLkRXAeuZ3HiKHmwy1/qZaS4RJW05oSlcHNCKwu
// SIG // 4Ij8Az3EtKT5o3buYvEHM98Cbqx4ODxyjZujoqag/mCG
// SIG // M86TEkApKCIYQIFq3UrVkS9zgbUzWi5gJYRu+0swMZ1a
// SIG // k5N1z8rG5BuHurMywy78xh9zWt9BgVlH3skffowmh+ju
// SIG // buH7FNd8qyUx5Wfzndz6TboaeOhWbCAf+z0UXqEiFku7
// SIG // BErzILhv3EAGGltBqHuYduM2qD1UXQlnpBwgsKVnoWPI
// SIG // Su//ISpOlabgGlX2V6v2Qq8z
// SIG // End signature block
