WScript.Echo("Hello");

// SIG // Begin signature block
// SIG // MIIFmQYJKoZIhvcNAQcCoIIFijCCBYYCAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // sXxazsqpG/T3QIroU6/9lozjalwO4B9PnVFFwkvRE4yg
// SIG // ggMUMIIDEDCCAfigAwIBAgIQTYdQj64z1LlOBslHxqye
// SIG // CTANBgkqhkiG9w0BAQsFADAgMR4wHAYDVQQDDBVBcmNh
// SIG // ZGUgU2lnbkNoZWNrIFRlc3QwHhcNMjYwODIwMTM1NDU1
// SIG // WhcNMjcwODIwMTQxNDU1WjAgMR4wHAYDVQQDDBVBcmNh
// SIG // ZGUgU2lnbkNoZWNrIFRlc3QwggEiMA0GCSqGSIb3DQEB
// SIG // AQUAA4IBDwAwggEKAoIBAQC3I8e4EnxVz02Hm7AQW76l
// SIG // ExaNc+p1t6pRp/Q0zDcRH1un8DE7jzH6IHYnzuZr6TtX
// SIG // EGFExYoGqSpi2EEnYAgX3TnYlhpZzIVBYBRoBlVhME4F
// SIG // KuPNGNpfgLXoOBIz/eueWO/zvrKzolLMfcJpC8fqeZAF
// SIG // ah3I9rx8cTDCVJxT4fWtvNioW8/D2gLz1CnTE/TsHoug
// SIG // TnIqI/sZd8R1zVFfborxb8Yku1zAw1bCJwkKO10HgJ4I
// SIG // BaIdGgD+GJ2klw+49g9loPkUOumU4pxWM0bmaGSYfcFi
// SIG // SfJ4+iVhU6DiZFcib+EIVFFeLwWTlYkXStnBO7mTn9Fu
// SIG // vEND6rdsb2SNAgMBAAGjRjBEMA4GA1UdDwEB/wQEAwIH
// SIG // gDATBgNVHSUEDDAKBggrBgEFBQcDAzAdBgNVHQ4EFgQU
// SIG // kCIsL9HE0TI36lzXoQSFFKO7Zw4wDQYJKoZIhvcNAQEL
// SIG // BQADggEBAEgKQArl2mRQ6mWGS25GEkWs0VYOxa/Q/o/H
// SIG // C6nEKcUsONPcmBxX9bAAXwWhmhLtKSXytYqTcHkLO1xc
// SIG // jYnxP2N3t+990NRG/vGiAtXphhgZBkgPUQ2oaVHcDI2L
// SIG // /0Yx1etGpEyikNiWCXmf0Wyy4tV/bcvBsFBvMvefkaQd
// SIG // 5YaXmILcddH9/GO6VYayh+vxBsWg9KhL3Go90FHGWugl
// SIG // To2NyUN59Pv9onFrpVPRB0U4q+bi6ycJA3CIkjBPX3bB
// SIG // P82VcCfH0zoMI3wPi9H7/uDnKpToX6Txbywp7ao1HDX9
// SIG // 8YjUiZdnudfjASFPhAYhUEe9C/k9l9AqmyMZEB9gdjUx
// SIG // ggHdMIIB2QIBATA0MCAxHjAcBgNVBAMMFUFyY2FkZSBT
// SIG // aWduQ2hlY2sgVGVzdAIQTYdQj64z1LlOBslHxqyeCTAN
// SIG // BglghkgBZQMEAgEFAKB8MBAGCisGAQQBgjcCAQwxAjAA
// SIG // MBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisG
// SIG // AQQBgjcCAQsxDjAMBgorBgEEAYI3AgEVMC8GCSqGSIb3
// SIG // DQEJBDEiBCBHA7P70NNFAqgzhCw91qEqUf9dE8pY5JeN
// SIG // sD3bDO4XyjANBgkqhkiG9w0BAQEFAASCAQCaTXZwOmO8
// SIG // p/2SLlMaZLMcCNKMMxF/RdhEKK40tRyiuRgOhWZS4ppx
// SIG // 6fp4CoPOSFhDMzQzk/DasaXBMCqh3GiosRDmHNmpmtJI
// SIG // PHl46qOuq95xDhw6LfOv43JZ3BR4KjMfNocMOg0fsROe
// SIG // bBYnevhCH0X3OgTq6/9pTNecOyhyPuqV9Vg0treLzWnJ
// SIG // +F4HEoRRo4MNY+MZ/MoxvoXQ6YmRDsZoOdetR7LUdqOR
// SIG // ux9K44fbbrINRl3+uFFrla96uy0ccY+YMx954dRXiCnE
// SIG // mVn8gm+Tz/qXgTTnaOGc5jzomhHsESpZj7E1h9aGx2SI
// SIG // NxdLLorbmLLHmvCoPle485J3
// SIG // End signature block
